language: node_js
node_js:
  - lts/*
services:
  - mongodb

  before_script:
  - mongo mongodb+srv://p2p-development:exhangep2p@cluster0-bep3r.mongodb.net/test --eval 
  env:
  global:
    - MONGODB_VERSION=2.6.10